### ISSUE TITLE
setting a locale doesn't affect the initial value

### ISSUE THREAD

**Issue by gcanti** [buildo/react-datepicker#21]
How to reproduce:

- set the locale to `en-GB`
- pass a default value to the datepicker

```js
// example
<DatePicker locale='en-GB' date={new Date()} />
```

displays `07/04/2015` instead of `04/07/2015`

**Comment by FrancescoCioria** [comment]
are you importing ```moment/locale/en-gb.js``` ?

**Comment by gcanti** [comment]
I'm just dumb, I didn't see this section in the docs, sorry

https://github.com/buildo/react-datepicker#locales

At least I spotted 2 typos:

- `theu support`
- should be `rc-datepicker/node_modules/moment/locale/fr.js` instead of `rc-datepicker/node_modules/locale/fr.js`

**Comment by gabro** [comment]
@FrancescoCioria is there any way you can warn if the locale chosen is not a available at runtime in development builds?

**Comment by FrancescoCioria** [comment]
Yes, we can check the current locale with '''moment.locale()'''. I'll create another issue

**Comment by gabro** [comment]
Consider also that there might be several locales imported. We want to check whether the one the user passes in as a prop is one of them
